import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider, Stack } from "@mantine/core";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "@mantine/core/styles.layer.css";
import "../global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
        <MantineProvider defaultColorScheme="dark">
          <Stack mih="100vh">
            <Header />
            <main>{children}</main>
            <Footer />
          </Stack>
        </MantineProvider>
      </body>
    </html>
  );
}
