import type { Metadata } from "next";

import HeaderComponent from "@/components/Header";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <head>
      <ColorSchemeScript />
    </head>
    <body>
      <MantineProvider>
        <HeaderComponent />
        <main>{children}</main>
      </MantineProvider>
    </body>
  </html>
);

export default RootLayout;
